### ISSUE TITLE
`domain` of virtualhosts not logged 

### ISSUE THREAD

**Issue by kennethgillen** [openmicroscopy/ansible-role-nginx-proxy#17]
Multiple virtualhosts created with config like:

```
- nginx_proxy_server_name: vhost1.openmicroscopy.org
  nginx_proxy_direct_locations:
  - location: /
    redirect301: "$scheme://a-server.openmicroscopy.org/about/thing.html"

- nginx_proxy_server_name: vhost2.openmicroscopy.org
  nginx_proxy_ssl: False
  nginx_proxy_direct_locations:
  - location: /
    redirect302: "https://other-server.org"
```

end up all logging to the same `/var/log/nginx` with no `domain` field, so the `vhost` is dropped, and not logged. i.e. requests to `vhost1.o.org/` and `vhost2.o.org/` are all logged as `/`
